--PESQUISAR AS OBRAS DE UM AUTOR ESPECIFICO 

SELECT O.ID, O.Titulo_Principal, A.Nome AS Autor
FROM OBRA O
JOIN AUTORES A ON O.FK_Autores_ID = A.ID
WHERE A.Nome = 'Joao Silva';

-- LISTA TODA AS REVISTA
SELECT ID, Titulo_Principal, ISSN, Volume, Periodicidade
FROM OBRA
WHERE Tipo = 'Revista';

-- BUSCA TODO OS LIVROS COM ISBN PREENCHIDO
SELECT Titulo_Principal, ISBN, Numero_Chamada
FROM OBRA
WHERE ISBN IS NOT NULL AND Tipo = 'Livro';

-- LISTA OBRAS POR ASSUNTOS COM JOIN
SELECT O.Titulo_Principal, S.Assunto
FROM OBRA O
JOIN ASSUNTOS S ON O.FK_Assunto_ID = S.ID
ORDER BY S.Assunto;

-- VER QUANTOS EXEMPLARES EXISTEM POR OBRA
SELECT O.Titulo_Principal, COUNT(E.Codigo) AS Total_Exemplares
FROM OBRA O
LEFT JOIN EXEMPLAR E ON O.ID = E.FK_OBRA_ID
GROUP BY O.Titulo_Principal;

--AUTORES SEGUNDARIOS DE CADA OBRA
SELECT O.Titulo_Principal, A.Nome AS Autor_Secundario
FROM SECUNDARIOS S
JOIN OBRA O ON S.FK_OBRA_ID = O.ID
JOIN AUTORES A ON S.FK_AUTORES_ID = A.ID;

-- TRAZER AS OBRAS COM SUA EDITORA
SELECT O.Titulo_Principal, E.Nome AS Editora
FROM OBRA O
JOIN EDITORA E ON O.FK_Editora_ID = E.ID;

-- VER TODOS OS EXEMPLARES DISPONIVEIS
SELECT E.Codigo, E.Numero, O.Titulo_Principal
FROM EXEMPLAR E
JOIN OBRA O ON E.FK_OBRA_ID = O.ID
WHERE E.Disponibilidade = 'Disponivel';

-- PESQUISA LIVROS POR PARTE
SELECT ID, Titulo_Principal
FROM OBRA
WHERE Titulo_Principal LIKE '%Programacao%';

-- LISTA TODAS AS OBRAS JUNTO COM O AUTOR PRINCIPAL E TODOS OS AUTORES SECUNDARIOS
SELECT 
    O.Titulo_Principal,
    A.Nome AS Autor_Principal,
    STRING_AGG(A2.Nome, ', ') AS Autores_Secundarios
FROM OBRA O
JOIN AUTORES A ON O.FK_Autores_ID = A.ID
LEFT JOIN SECUNDARIOS S ON O.ID = S.FK_OBRA_ID
LEFT JOIN AUTORES A2 ON S.FK_AUTORES_ID = A2.ID
GROUP BY O.Titulo_Principal, A.Nome;
