CREATE DATABASE MUSEU;
USE MUSEU;

-- AUTORES
CREATE TABLE AUTORES (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Nome VARCHAR(200),
    Nacionalidade CHAR(3)
)
GO

-- ASSUNTOS
CREATE TABLE ASSUNTOS (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Assunto VARCHAR(500)
)
GO

-- EDITORA
CREATE TABLE EDITORA (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Nome VARCHAR(200)
)
GO


-- OBRA
CREATE TABLE OBRA (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,

    Titulo_Principal VARCHAR(500),
    Capa VARCHAR(100),
    Local VARCHAR(100),
    Data VARCHAR(20),
    Desc_Fisica VARCHAR(500),
    Numero_Chamada VARCHAR(20),
    Chamada_Local VARCHAR(20),
    Titulo_Uniforme VARCHAR(200),
    ISBN CHAR(13),
    Serie INT,
    Edicao INT,
    Colecao VARCHAR(100),
    Notas_Gerais VARCHAR(500),
    ISSN CHAR(8),
    Volume INT,
    Periodicidade VARCHAR(50),
    Nome VARCHAR(200),
    Tipo VARCHAR(10),  

    -- FKs conforme o diagrama
    FK_Assunto_ID INT NOT NULL,
    FK_Editora_ID INT NOT NULL,
    FK_Autores_ID INT NOT NULL,

    FOREIGN KEY (FK_Assunto_ID) REFERENCES ASSUNTOS(ID),
    FOREIGN KEY (FK_Editora_ID) REFERENCES EDITORA(ID),
    FOREIGN KEY (FK_Autores_ID) REFERENCES AUTORES(ID)
)
GO


-- EXEMPLAR 
CREATE TABLE EXEMPLAR (
    Codigo INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Disponibilidade VARCHAR(50),
    Numero INT,
    FK_OBRA_ID INT NOT NULL,

    FOREIGN KEY (FK_OBRA_ID) REFERENCES OBRA(ID)
)
GO


-- SECUNDARIOS 
CREATE TABLE SECUNDARIOS (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,

    FK_OBRA_ID INT NOT NULL,
    FK_AUTORES_ID INT NOT NULL,

    FOREIGN KEY (FK_OBRA_ID) REFERENCES OBRA(ID),
    FOREIGN KEY (FK_AUTORES_ID) REFERENCES AUTORES(ID)
)
GO
